apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  description: Production workloads managed by GitOps

  sourceRepos:
    - https://github.com/limitedbug/infrastructure.git

  destinations:
    - namespace: simple-coffee
      server: https://kubernetes.default.svc

    - namespace: default
      server: https://kubernetes.default.svc

    - namespace: arcadia
      server: https://kubernetes.default.svc

    - namespace: quality-clean
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: gateway.networking.k8s.io
      kind: GatewayClass

  namespaceResourceWhitelist:
    - group: gateway.networking.k8s.io
      kind: Gateway

    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    
    - group: argoproj.io
      kind: Application
