apiVersion: v1
kind: Service
metadata:
  name: arcadia
spec:
  type: ClusterIP
  selector:
    app: arcadia
  ports:
    - name: http
      port: 80
      targetPort: http
  sessionAffinity: ClientIP
