apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arcadia-production
  namespace: argocd
spec:
  project: production

  source:
    repoURL: https://github.com/limitedbug/infrastructure.git
    targetRevision: main
    path: apps/arcadia/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: arcadia

  syncPolicy:
    automated:
      selfHeal: true
      prune: false
