apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: default
spec:
  gatewayClassName: envoy-gateway

  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: https-arcadia
      protocol: HTTPS
      port: 443
      hostname: arcadia.good-robert.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: arcadia-good-robert-com-tls
            namespace: arcadia
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: https-good-robert
      protocol: HTTPS
      port: 443
      hostname: good-robert.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: good-robert-com-tls
            namespace: default
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: https-monitor
      protocol: HTTPS
      port: 443
      hostname: monitor.good-robert.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: good-robert-com-tls
            namespace: default
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: https-status
      protocol: HTTPS
      port: 443
      hostname: status.good-robert.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: good-robert-com-tls
            namespace: default
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: https-vault
      protocol: HTTPS
      port: 443
      hostname: vault.good-robert.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: good-robert-com-tls
            namespace: default
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All

    - name: https-simple-coffee
      protocol: HTTPS
      port: 443
      hostname: simple-coffee.com
      tls:
        mode: Terminate
        certificateRefs:
          - name: good-robert-com-tls
            namespace: default
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
