apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arcadia-good-robert-com-tls
spec:
  secretName: arcadia-good-robert-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - arcadia.good-robert.com
